---
title: "TCR_T_sub2"
author: "Zhu Ni"
date: "`r Sys.Date()`"
output: html_document
---

## 1.Load data
```{r}
library(Seurat)
library(dplyr)
library(ggplot2)

# sce <- readRDS("../../../CASH/tmp/sce_Tcell_TCR.rds")
sce <- readRDS("../../data/obj/T_obj.rds")

Clonalsize_color_panel <- c(
  "Hyperexpanded (0.1 < X <= 1)" = "#78290f",
  "Large (0.01 < X <= 0.1)" = "#78290f",
  "Medium (0.001 < X <= 0.01)" = "#ff7d10",
  "Small (1e-04 < X <= 0.001)" = "#ffecd1",
  "Rare (0 < X <= 1e-04)" = "#FFF9DA",
  "None ( < X <= 0)" = "#BFBFBF")

Subset_color_panel <- c(
  # T
  "0" = "#a82d06",
  "1" = "#4592bf",
  "2" = "#d38219",
  "3" = "#74a764",
  "4" = "#8ca2b4",
  "5" = "#cbb190",
  "6" = "#e7ca8d",
  "7" = "#9d9ec3",
  "8" = "#593202",
  # ASC
  "9" = "#ebafa4",
  "10" = "#5e8a89",
  "11" = "#ecd577",
  "12" = "#7c606c",
  "13" = "#5c6489"
)
```
## 2.UMAP
```{r}
Idents(sce) <- "RNA_snn_res.0.7"
ggplot(sce@reductions$umap.cca@cell.embeddings, aes(x = umapcca_1, y = umapcca_2, color = sce@active.ident)) +
  geom_point(size = 0.01,
             shape = 16,
             stroke = 0) +
  theme_void()+
  scale_color_manual(values = Subset_color_panel, name = '')+
  theme(aspect.ratio = 1,
        legend.position = "none")
```

## match meta
```{r fig.width=10,fig.height=6}
sce_TCR <- readRDS("../../../CASH/tmp/sce_Tcell_TCR.rds")
meta_tcr <- sce_TCR@meta.data
# meta_tcr$barcode <- rownames(meta_tcr)
# meta_tcr <- meta_tcr[, c("barcode", "cloneSize")]

meta_t <- sce@meta.data
meta_match <- meta_tcr[match(rownames(meta_t), rownames(meta_tcr)),]
meta_t$cloneSize <- meta_match$cloneSize
sce@meta.data <- meta_t
```

```{r}
n_cluster_raw <- sce_TCR@meta.data %>%
  group_by(group, cloneSize) %>%
  summarize(count = n()) %>%
  mutate(proportion = count / sum(count) * 100) %>%
  ungroup()

n_cluster_new <- sce@meta.data %>%
  group_by(group, cloneSize) %>%
  summarize(count = n()) %>%
  mutate(proportion = count / sum(count) * 100) %>%
  ungroup()
```


## 3.Count of TCR clones
```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=6}
# tmp <- meta_t
tmp <- sce@meta.data
tmp <- tmp[, c("group", "orig.ident", "cloneSize")]
tmp <- na.omit(tmp)
tmp <- table(tmp) %>% 
  as.data.frame() %>%
  group_by(group, orig.ident) %>%
  summarise(Count = sum(Freq))
colnames(tmp)[2] <- "Donor"

ggplot(tmp, aes(x = Donor, y = Count, fill = group)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("CASH" = "#0f7b9f", "Normal" = "#d83215"),
                    name = "CloneSize") +
  cowplot::theme_cowplot() +
  coord_flip() +
  xlab("") + ylab("Count") +
  theme(
    axis.text.x = element_text(size = 7, angle = 0),
    text = element_text(size = 7),
    axis.line = element_line(size = 0.3),
    axis.ticks = element_line(size = 0.3),
    axis.text.y = element_text(size = 7, angle = 0),
    axis.ticks.y = element_blank(),
    axis.line.y = element_blank(),
    panel.border = element_blank(),
    legend.position = "none"
  ) + 
  guides(fill = guide_legend(ncol = 3))
```

## 4.Proportion
```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=6}
tmp <- meta_t
tmp$cloneSize <- as.character(tmp$cloneSize)
tmp$cloneSize[is.na(tmp$cloneSize)] <- "None ( < X <= 0)"

# tmp <- sc@meta.data
tmp <- tmp[, c("RNA_snn_res.0.7", "group", "cloneSize")]
tmp <- table(tmp) %>% 
  as.data.frame() 
colnames(tmp)[1] <- "cluster" 



p <- ggplot(tmp, aes(x = cluster, y = Freq, fill = as.character(cloneSize))) +
  geom_bar(stat = "identity", position = "fill") +
  scale_fill_manual(values = Clonalsize_color_panel,
                    name = "CloneSize") +
  facet_grid(~group, scales = "free") +
  cowplot::theme_cowplot() +
  xlab("") + ylab("Proportion") +
  theme(
    axis.text.x = element_text(size = 7, angle = 0, hjust = 1, vjust = 0.5),
    axis.text.y = element_text(size = 7),
    text = element_text(size = 8),
    plot.margin = unit(c(1, 1, 1, 1), "char"),
    axis.line = element_line(size = 0.3),
    axis.ticks = element_line(size = 0.3),
    legend.position = "bottom"
  ) + 
  guides(fill = guide_legend(ncol = 3))

# pdf("../fig/TCR_propotion.pdf", width = 10, height = 6)
print(p)
# dev.off()
```



```{r fig.width=10,fig.height=6}
colorblind_vector <- hcl.colors(n=7, palette = "inferno", fixup = TRUE)

# DimPlot(sce, split.by = "group", label = T,
#         pt.size = 0.5, order = T, shuffle  = T, raster=FALSE, reduction = "umap.cca") +
#   scale_color_manual(values = Subset_color_panel)+
#   NoLegend()
p1 <- DimPlot(sce, group.by = "cloneSize", split.by = "group",
        pt.size = 0.5, order = T, shuffle  = T, raster=FALSE, reduction = "umap.cca") +
  scale_color_manual(values=rev(colorblind_vector[c(1,3,4,5,7)]))
print(p1)

sce@meta.data[c("UMAP1", "UMAP2")] <- Embeddings(sce, reduction = "umap.cca")
tmp <- sce@meta.data
p2 <- ggplot(tmp, aes(x = UMAP1, y = UMAP2, color = cloneSize)) +
  ## panel
  geom_point(size = 0.8, shape = 16, stroke = 0) +
  theme_void() +
  ## split
  facet_wrap(~ group) +
  ## color
  scale_color_manual(values = rev(colorblind_vector[c(1,3,4,5,7)]), name = '') +
  theme(
    aspect.ratio = 1,
    ## facet
    strip.text.x = element_text(size = 12, face = "bold"),
    strip.background = element_rect(color = NA, fill = NA, size = 1),
    
    ## legend
    legend.text = element_text(size = 12),
    legend.spacing.y = unit(0, 'cm'),
    legend.key.height = unit(0,"cm"),
    legend.box.spacing = unit(0, 'cm'),
    legend.position = "right") +
  guides(color = guide_legend(ncol = 1, override.aes = list(size = 5, alpha = 1)))
print(p2)
```

